# Generated by Django 3.0.7 on 2020-06-10 20:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disty', '0002_auto_20200610_2015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='DownloadUrl',
        ),
    ]
