# Generated by Django 3.0.7 on 2020-06-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disty", "0004_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="access",
            name="source_ip",
            field=models.GenericIPAddressField(default="0.0.0.0"),
            preserve_default=False,
        ),
    ]
