# Generated by Django 3.0.7 on 2020-06-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disty', '0004_uploadurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadurl',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
