# Generated by Django 3.0.7 on 2020-06-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disty', '0005_uploadurl_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadurl',
            name='download_count',
        ),
        migrations.AddField(
            model_name='downloadurl',
            name='download_limit',
            field=models.IntegerField(default=1),
        ),
    ]
