# Generated by Django 3.0.7 on 2020-06-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disty', '0006_auto_20200613_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadurl',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
