# Generated by Django 3.0.7 on 2020-06-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disty', '0007_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='file',
            name='document',
            field=models.FileField(default='something', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
