# Generated by Django 3.0.7 on 2020-06-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disty', '0008_auto_20200607_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
