# Generated by Django 3.0.7 on 2020-06-07 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disty', '0009_auto_20200607_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
