import os

DEFAULT_DOWNLOAD_LIMIT = int(os.environ.get("DEFAULT_DOWNLOAD_LIMIT", 1))
DEFAULT_DOWNLOAD_EXPIRY_DAYS = int(os.environ.get("DEFAULT_DOWNLOAD_EXPIRY_DAYS", 1))
DEFAULT_UPLOAD_URL_EXPIRY_DAYS = int(
    os.environ.get("DEFAULT_UPLOAD_URL_EXPIRY_DAYS", 10)
)
UPLOAD_FOLDER = os.environ.get("UPLOAD_FOLDER", "documents/")
